from __future__ import annotations

import uuid
from typing import Annotated

from fastapi import Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.db import SessionDep
from app.domain import TranslatedQuestions
from app.models import UserQuestion
from app.repositories import QuestionRepository
from app.services.ai import QuestionAI, get_question_ai
from app.services.users import UserService


class QuestionService:
    """Saved "Ask the staff" questions (Settings -> My questions).

    Questions are per-user rows kept in list order; the ask-staff sheet shows
    them verbatim and translates on demand. Suggestions are generated by the
    QuestionAI adapter from the user's active "Watch out for" chips, in their
    preferred language, skipping anything they already saved.
    """

    def __init__(self, session: AsyncSession, ai: QuestionAI | None = None):
        self.session = session  # owns the transaction boundary
        self.questions = QuestionRepository(session)
        self.users = UserService(session)  # for prefs (watch chips + language)
        self.ai = ai or get_question_ai()

    async def list(self, user_id: uuid.UUID) -> list[UserQuestion]:
        return await self.questions.list_for_user(user_id)

    async def add(self, user_id: uuid.UUID, text: str) -> UserQuestion:
        """Append a question at the end of the user's list."""
        question = UserQuestion(
            user_id=user_id,
            text=text,
            position=await self.questions.next_position(user_id),
        )
        self.questions.add(question)
        await self.session.commit()
        return question

    async def remove(self, user_id: uuid.UUID, question_id: uuid.UUID) -> bool:
        """Delete one of the user's questions; False if it isn't theirs.

        Remaining rows keep their positions — order only needs to be
        monotonic, not dense, and the next reorder renumbers everything.
        """
        question = await self.questions.get(question_id)
        if question is None or question.user_id != user_id:
            return False
        await self.questions.delete(question)
        await self.session.commit()
        return True

    async def reorder(self, user_id: uuid.UUID, ids: list[uuid.UUID]) -> list[UserQuestion]:
        """Rewrite positions to match `ids` (the full list, dragged order).

        Raises ValueError unless `ids` is exactly the user's current set —
        the reorder UI always sends everything, so a mismatch means a stale
        client, and applying it would silently drop or duplicate rows.
        """
        current = await self.questions.list_for_user(user_id)
        # Multiset compare: catches missing, extra, foreign and duplicated ids
        # in one go (current ids are distinct PKs, so any dup can't match).
        if sorted(ids) != sorted(q.id for q in current):
            raise ValueError("ids must be exactly the user's current questions")
        by_id = {q.id: q for q in current}
        for position, question_id in enumerate(ids):
            by_id[question_id].position = position
        await self.session.commit()
        return [by_id[question_id] for question_id in ids]

    async def suggest(self, user_id: uuid.UUID) -> tuple[list[str], list[str]]:
        """(watch keys the suggestions are based on, suggested questions).

        Based on the user's active watch chips; empty when nothing is watched
        (nothing to seed the prompt with). Already-saved questions are passed
        to the AI so it doesn't repeat them.
        """
        prefs = await self.users.get_preferences(user_id)
        chips = [c for c in prefs.watch_list if c.on]
        if not chips:
            return [], []
        existing = [q.text for q in await self.questions.list_for_user(user_id)]
        suggestions = await self.ai.suggest_questions(chips, prefs.language, existing)
        return [c.key for c in chips], suggestions

    async def translate(
        self, texts: list[str], dish_name: str, origin: str | None, language: str | None
    ) -> TranslatedQuestions:
        """Translate questions for the ask-staff sheet (see QuestionAI).

        `language` is the menu's stored language when the client knows it;
        without one the AI infers it from the dish. Stateless — nothing is
        persisted; the device caches translations per target language.
        """
        normalized = language.strip().lower()[:2] if language else None
        return await self.ai.translate_questions(
            texts, dish_name=dish_name, origin=origin, language=normalized or None
        )


def get_question_service(session: SessionDep) -> QuestionService:
    return QuestionService(session)


QuestionServiceDep = Annotated[QuestionService, Depends(get_question_service)]
