"""currencies table with eur rates

Revision ID: 193cb8eb7cf7
Revises: 5bb1bbda45d4
Create Date: 2026-07-08 19:31:00.249290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193cb8eb7cf7'
down_revision: Union[str, Sequence[str], None] = '5bb1bbda45d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('rate_per_eur', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate_per_eur > 0', name='ck_currencies_rate_positive'),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###

    # Seed a starter set so the currency dropdown works out of the box.
    # Rates are approximate snapshots (units per 1 EUR) — the daily refresh
    # task will overwrite them; only `code` is load-bearing.
    op.execute(
        """
        INSERT INTO currencies (code, name, symbol, rate_per_eur) VALUES
        ('EUR', 'Euro', '€', 1),
        ('USD', 'US dollar', '$', 1.08),
        ('GBP', 'British pound', '£', 0.85),
        ('CZK', 'Czech koruna', 'Kč', 25.0),
        ('PLN', 'Polish złoty', 'zł', 4.3),
        ('HUF', 'Hungarian forint', 'Ft', 395.0),
        ('CHF', 'Swiss franc', 'CHF', 0.94),
        ('SEK', 'Swedish krona', 'kr', 11.3),
        ('NOK', 'Norwegian krone', 'kr', 11.6),
        ('DKK', 'Danish krone', 'kr', 7.46),
        ('RON', 'Romanian leu', 'lei', 4.97),
        ('JPY', 'Japanese yen', '¥', 168.0),
        ('CNY', 'Chinese yuan', '¥', 7.8),
        ('KRW', 'South Korean won', '₩', 1480.0),
        ('THB', 'Thai baht', '฿', 39.5),
        ('VND', 'Vietnamese dong', '₫', 27500.0),
        ('IDR', 'Indonesian rupiah', 'Rp', 17500.0),
        ('INR', 'Indian rupee', '₹', 90.0),
        ('TRY', 'Turkish lira', '₺', 35.0),
        ('MXN', 'Mexican peso', '$', 19.5),
        ('BRL', 'Brazilian real', 'R$', 6.0),
        ('CAD', 'Canadian dollar', '$', 1.47),
        ('AUD', 'Australian dollar', '$', 1.64),
        ('NZD', 'New Zealand dollar', '$', 1.77)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    # ### end Alembic commands ###
