"""initial schema

Consolidated baseline — the incremental 2026-07 migrations were squashed into
this one before any shared environment existed; older databases are not
upgradable and should be dropped and recreated.

Revision ID: 1fcf61e22684
Revises:
Create Date: 2026-07-09 15:43:31.359271

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fcf61e22684'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any table uses the VECTOR type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('rate_per_eur', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate_per_eur > 0', name='ck_currencies_rate_positive'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('dishes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_canonical_name'), 'dishes', ['canonical_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_table('dish_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('base_value', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind IN ('allergen', 'dietary')) = (key IS NOT NULL)", name='ck_dish_attributes_key_presence'),
    sa.CheckConstraint('value BETWEEN 0 AND 100', name='ck_dish_attributes_value_range'),
    sa.CheckConstraint('base_value BETWEEN 0 AND 100', name='ck_dish_attributes_base_value_range'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_attributes_dish_id'), 'dish_attributes', ['dish_id'], unique=False)
    op.create_index('uq_dish_attributes_dish_kind_key', 'dish_attributes', ['dish_id', 'kind', 'key'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('dish_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_photos_dish_id'), 'dish_photos', ['dish_id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_user_id'), 'menus', ['user_id'], unique=False)
    op.create_table('user_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_questions_user_id'), 'user_questions', ['user_id'], unique=False)
    op.create_table('dish_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('direction IN (-1, 1)', name='ck_dish_votes_direction'),
    sa.ForeignKeyConstraint(['attribute_id'], ['dish_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_votes_attribute_id'), 'dish_votes', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_dish_votes_user_id'), 'dish_votes', ['user_id'], unique=False)
    op.create_index('uq_dish_votes_attribute_user', 'dish_votes', ['attribute_id', 'user_id'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_image_sha256'), 'scans', ['image_sha256'], unique=False)
    op.create_index(op.f('ix_scans_menu_id'), 'scans', ['menu_id'], unique=False)
    op.create_table('scan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('menu_number', sa.String(length=16), nullable=True),
    sa.Column('translated_name', sa.String(length=255), nullable=True),
    sa.Column('menu_description', sa.Text(), nullable=True),
    sa.Column('menu_description_translated', sa.Text(), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('group_name_translated', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('menu_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('menu_price_currency', sa.String(length=3), nullable=True),
    sa.Column('regional_note', sa.Text(), nullable=True),
    sa.Column('dish_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_items_dish_id'), 'scan_items', ['dish_id'], unique=False)
    op.create_index(op.f('ix_scan_items_scan_id'), 'scan_items', ['scan_id'], unique=False)
    # ### end Alembic commands ###

    # Seed a starter set so the currency dropdown works out of the box.
    # Rates are approximate snapshots (units per 1 EUR) — the daily refresh
    # task will overwrite them; only `code` is load-bearing.
    op.execute(
        """
        INSERT INTO currencies (code, name, symbol, rate_per_eur) VALUES
        ('EUR', 'Euro', '€', 1),
        ('USD', 'US dollar', '$', 1.08),
        ('GBP', 'British pound', '£', 0.85),
        ('CZK', 'Czech koruna', 'Kč', 25.0),
        ('PLN', 'Polish złoty', 'zł', 4.3),
        ('HUF', 'Hungarian forint', 'Ft', 395.0),
        ('CHF', 'Swiss franc', 'CHF', 0.94),
        ('SEK', 'Swedish krona', 'kr', 11.3),
        ('NOK', 'Norwegian krone', 'kr', 11.6),
        ('DKK', 'Danish krone', 'kr', 7.46),
        ('RON', 'Romanian leu', 'lei', 4.97),
        ('JPY', 'Japanese yen', '¥', 168.0),
        ('CNY', 'Chinese yuan', '¥', 7.8),
        ('KRW', 'South Korean won', '₩', 1480.0),
        ('THB', 'Thai baht', '฿', 39.5),
        ('VND', 'Vietnamese dong', '₫', 27500.0),
        ('IDR', 'Indonesian rupiah', 'Rp', 17500.0),
        ('INR', 'Indian rupee', '₹', 90.0),
        ('TRY', 'Turkish lira', '₺', 35.0),
        ('MXN', 'Mexican peso', '$', 19.5),
        ('BRL', 'Brazilian real', 'R$', 6.0),
        ('CAD', 'Canadian dollar', '$', 1.47),
        ('AUD', 'Australian dollar', '$', 1.64),
        ('NZD', 'New Zealand dollar', '$', 1.77)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_items_scan_id'), table_name='scan_items')
    op.drop_index(op.f('ix_scan_items_dish_id'), table_name='scan_items')
    op.drop_table('scan_items')
    op.drop_index(op.f('ix_scans_menu_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_image_sha256'), table_name='scans')
    op.drop_table('scans')
    op.drop_index('uq_dish_votes_attribute_user', table_name='dish_votes')
    op.drop_index(op.f('ix_dish_votes_user_id'), table_name='dish_votes')
    op.drop_index(op.f('ix_dish_votes_attribute_id'), table_name='dish_votes')
    op.drop_table('dish_votes')
    op.drop_index(op.f('ix_user_questions_user_id'), table_name='user_questions')
    op.drop_table('user_questions')
    op.drop_index(op.f('ix_menus_user_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_dish_photos_dish_id'), table_name='dish_photos')
    op.drop_table('dish_photos')
    op.drop_index('uq_dish_attributes_dish_kind_key', table_name='dish_attributes', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_dish_attributes_dish_id'), table_name='dish_attributes')
    op.drop_table('dish_attributes')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dishes_canonical_name'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_table('currencies')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
