"""clerk users, menus, scans, dish attributes, votes

Revision ID: 5bb1bbda45d4
Revises: e60b6087f7db
Create Date: 2026-07-08 19:09:07.671012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bb1bbda45d4'
down_revision: Union[str, Sequence[str], None] = 'e60b6087f7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_table('dish_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind IN ('allergen', 'dietary')) = (key IS NOT NULL)", name='ck_dish_attributes_key_presence'),
    sa.CheckConstraint('value BETWEEN 0 AND 100', name='ck_dish_attributes_value_range'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_attributes_dish_id'), 'dish_attributes', ['dish_id'], unique=False)
    op.create_index('uq_dish_attributes_dish_kind_key', 'dish_attributes', ['dish_id', 'kind', 'key'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_user_id'), 'menus', ['user_id'], unique=False)
    op.create_table('dish_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('direction IN (-1, 1)', name='ck_dish_votes_direction'),
    sa.ForeignKeyConstraint(['attribute_id'], ['dish_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_votes_attribute_id'), 'dish_votes', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_dish_votes_user_id'), 'dish_votes', ['user_id'], unique=False)
    op.create_index('uq_dish_votes_attribute_user', 'dish_votes', ['attribute_id', 'user_id'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_image_sha256'), 'scans', ['image_sha256'], unique=False)
    op.create_index(op.f('ix_scans_menu_id'), 'scans', ['menu_id'], unique=False)
    op.create_table('scan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('menu_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('menu_price_currency', sa.String(length=3), nullable=True),
    sa.Column('regional_note', sa.Text(), nullable=True),
    sa.Column('dish_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_items_dish_id'), 'scan_items', ['dish_id'], unique=False)
    op.create_index(op.f('ix_scan_items_scan_id'), 'scan_items', ['scan_id'], unique=False)
    op.drop_column('dish_photos', 'attribution')
    op.drop_column('dish_photos', 'license')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_photos', sa.Column('license', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('dish_photos', sa.Column('attribution', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scan_items_scan_id'), table_name='scan_items')
    op.drop_index(op.f('ix_scan_items_dish_id'), table_name='scan_items')
    op.drop_table('scan_items')
    op.drop_index(op.f('ix_scans_menu_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_image_sha256'), table_name='scans')
    op.drop_table('scans')
    op.drop_index('uq_dish_votes_attribute_user', table_name='dish_votes')
    op.drop_index(op.f('ix_dish_votes_user_id'), table_name='dish_votes')
    op.drop_index(op.f('ix_dish_votes_attribute_id'), table_name='dish_votes')
    op.drop_table('dish_votes')
    op.drop_index(op.f('ix_menus_user_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index('uq_dish_attributes_dish_kind_key', table_name='dish_attributes', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_dish_attributes_dish_id'), table_name='dish_attributes')
    op.drop_table('dish_attributes')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
